server:
  port: 8080 #set your port

logging:
  level:
    "liquibase" : info

spring:

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.3.66:5432/student_spring
    username: postgres
    password: Admin1992

  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

